/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab.eci.ocupados.gui;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
/**
 *
 * @author 2129082 y 2131608
 */
public class IngSoftware extends JPanel {

    private PanelMain frame;
    private Image background;
    
    
    /**
     * Creates new form ingSoftware
     */
    public IngSoftware(PanelMain main) {
        super();
        this.frame = main;
        initComponents();
        prepareElements();
        setOpaque(false);
        setFocusable(false);
    }

    private void prepareElements(){
        background = Toolkit.getDefaultToolkit().createImage(getClass().getResource("/img/IngSoftware&Salita.PNG"));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    @Override
    public void paint(Graphics g){
        g.drawImage(background,0,0,frame.getWidth(), frame.getHeight(), this);
        super.paint(g);
    }

}
